[mongodb]
mongodb.daws-sunny.site

[catalogue]
catalogue.daws-sunny.site

[redis]
redis.daws-sunny.site

[user]
user.daws-sunny.site

[cart]
cart.daws-sunny.site

[frontend]
frontend.daws-sunny.site

[mysql]
mysql.daws-sunny.site

[payment]
payment.daws-sunny.site

[rabbitmq]
rabbitmq.daws-sunny.site

[shipping]
shipping.daws-sunny.site

[local]
localhost