[mongodb]
mongodb.daws-sunny.site

[catalogue]
catalogue.daws-sunny.site

[redis]
redis.daws-sunny.site

[user]
user.daws-sunny.site

[cart]
cart.daws-sunny.site

[frontend]
frontend.daws-sunny.site

[local]
localhost