- name: setup rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
    - name: copy repo to directory
      ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: installed

    - name: enable and start service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: add user and permissions
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        permissions:
          - vhost: "/"
            configure_priv: "^$"
            read_priv: ".*"
            write_priv: ".*"
        state: present
